JobPortal/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('choose_register' , views.choose_register , name='choose_register'),
    path('signup/', views.registration_view, name="signup"),
    path('register_company_front/', views.register_company_front, name='register_company_front'),
    path('job-list/', views.job_list, name='job-list'),
    path('job_search/<str:job_title>/<str:city>', views.job_search, name='job_search'),
    path('job-sector/<slug:slug>', views.job_sector_categories, name='job_sector_categories'),
    path('job-detail/<slug:slug>', views.job_detail, name='Job-detail'),

    #User
    path('user-add-bookmark/<slug:slug>', views.user_add_bookmark, name="user-add-bookmark"),
    path('user-remove-bookmark/<slug:slug>', views.user_delete_bookmark, name='user-delete-bookmark'),
    path('user-apply-job/<slug:slug>', views.user_apply_job, name='user-apply-job'),
    path('user-cancel-job/<slug:slug>', views.user_cancel_job, name='user-cancel-job'),
    path('resetpassword/', views.reset_password, name='reset-password'),
    path('login/', views.login, name='login'),
    path('user-dashboard/', views.user_dashboard, name='user-dashboard'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('user-add-resume/', views.user_resume, name='user-resume'),
    path('user-add-education/', views.user_add_education, name='user-add-education'),
    path('user-education/<slug:slug>/',views.detail_user_education, name='detail-user-education'),
    path('user-delete-education/<slug:slug>',views.user_delete_education, name='user-delete-education'),
    path('user-add-experience/', views.user_add_experience, name='user-add-experience'),
    path('user-experience/<slug:slug>/',views.detail_user_experience, name='detail-user-experience'),
    path('user-delete-experience/<slug:slug>',views.user_delete_experience, name='user-delete-experience'),
    path('user-add-project/', views.user_add_project, name='user-add-project'),
    path('user-project/<int:id>/',views.detail_user_project, name='detail-user-project'),
    path('user-delete-project/<int:id>',views.user_delete_project, name='user-delete-project'),

    
    path('user-add-certification/', views.user_add_certification, name='user-add-certification'),
    path('user-certification/<int:id>/',views.detail_user_certification, name='detail-user-certification'),
    path('user-delete-certification/<int:id>',views.user_delete_certification, name='user-delete-certification'),
    
    path('user-add-language/', views.user_add_language, name='user-add-language'),
    path('user-language/<int:id>/',views.detail_user_language, name='detail-user-language'),
    path('user-delete-language/<int:id>',views.user_delete_language, name='user-delete-language'),
    path('user-applied-job/', views.user_applied_jobs, name='user-applied-job'),
    path('user-bookmark/', views.user_bookmark, name='user-bookmark'),
    path('user-change-password/', views.user_change_password, name='user-change-password'),

    #Interviewer
    path('interviewer-dashboard/', views.interviewer_dashboard, name='interviewer-dashboard'),
    path('interviewer-info/', views.interviewer_personal_info, name='interviewer-personal-info'),
    path('interviewer-job-list/', views.interviewer_job_list, name='interviewer-job-list'),
    path('interviewer-job-detail/<slug:slug>', views.interviewer_job_detail, name='interviewer-job-detail'),
    path('interviewer-interviews-list/', views.interviewer_interviews_lists, name='interviewer-interviews-list'),
    path('interview-detail/<slug:slug>', views.interview_detail, name='interview_detail'),
    path('interview-scheduled/', views.interview_scheduled, name='interview-scheduled'),
    path('today-interviews/', views.interview_today_interview_list, name='today-interviews'),
    path('interview-now/<slug:slug>', views.interview_individual_now, name="interviews-now"),
    path('interview-job-status/', views.interview_candidate_job_status, name="interview-job-status"),
    path('interview-applicant-category/<slug:slug>', views.interview_applicant_category, name='interview_applicant_category'),
    path('company_interviewer_change_password/', views.company_interviewer_change_password, name='company_interviewer_change_password'),




    path('validate_skill_list/', views.validate_skill_list, name="validate_skill_list"),
    path('instruction/<str:id>/', views.instruction, name="instruction"),
    path('validate_skill/<str:id>/', views.validate_skill, name="validate_skill"),


    path('optimizer/', views.optimizer, name="optimizer"),





]

Seraye/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobPortal.urls')),
    path('company/', include('Company.urls')),
     path('interview/', include('Interview.urls')),
    path('user-management/', include('UserManagement.urls')),
    path('user-admin/', include('UserAdmin.urls')),
    path('company-admin/', include('CompanyAdmin.urls')),
    path('froala_editor/', include('froala_editor.urls')),
]
urlpatterns += debug_toolbar_urls()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

JobPortal/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from froala_editor.fields import FroalaField
from UserManagement.models import CustomUser
from django.utils.text import slugify
from unidecode import unidecode
from Company.models import Company
import datetime
from auditlog.registry import auditlog

#Candidate
gender_list = [
    ('male', 'Male'),
    ('female', 'Female'),
]



class Candidate(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.SET_NULL, null=True)
    gender = models.CharField(max_length=10, choices=gender_list)
    date_of_birth = models.DateField()
    email = models.EmailField(max_length=40)
    phone1 = PhoneNumberField()
    phone2 = PhoneNumberField(blank = True)
    address = models.CharField(max_length=100)
    linked_in = models.URLField(blank=True, null=True)
    country = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    photo = models.ImageField(upload_to='Candidate/photo', null=True, blank=True)
    about = models.TextField() 
    skill = models.ManyToManyField("Skill", blank=False) 
    slug = models.SlugField(unique=True, blank=True,  max_length=200)
    date_created = models.DateField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.first_name + " " + self.user.last_name
    
    def age(self):
        date = datetime.datetime.now()
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.user.username))
        super().save(*args, **kwargs)

education_status_list = [
    ('highschool', 'High School'),
    ('Certificate', 'Certificate'),
    ('diploma', 'Diploma'),
    ('bachelor-degree', "Bachelor's degree"),
    ('Master-degree', "Master's Degree"),
    ('doctorate', "Doctorate"),
    ('other', 'Other')
]


class UserSkill(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    skill = models.ForeignKey("Skill" ,  on_delete=models.CASCADE)
    validated = models.BooleanField(default=False)
   

    def __str__(self) -> str:
        return self.candidate.user.first_name + "" + self.skill.title

class Education(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    institution_name = models.CharField(max_length=100)
    education_status = models.CharField(max_length=40, choices=education_status_list)
    field_of_study = models.CharField(max_length=40)
    education_period_start = models.DateField()
    education_period_end = models.DateField()
    gpa = models.FloatField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, max_length=200)
    document = models.FileField(upload_to='media/educationDocument', null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) + "-" + slugify(unidecode(self.institution_name)) + "-" + slugify(unidecode(self.field_of_study))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.institution_name
    

class Experience(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    company_name = models.CharField(max_length=40)
    work_time_line_start =models.DateField()
    work_time_line_end = models.DateField()
    job_title = models.CharField(max_length=50)
    reference_phone = PhoneNumberField()
    reference_name = models.CharField(max_length=40)
    reference_email = models.CharField(max_length=40)
    reference_job_title = models.CharField(max_length=40)
    responsibility = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) +"-"+slugify(unidecode(self.company_name))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.company_name




class Certification(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    certification_name = models.CharField(max_length=100)
    issuing_organization = models.CharField(max_length=100)
    document = models.FileField(upload_to='media/certifications/', null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.certification_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.certification_name

    
class Project(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    project_type = models.CharField(max_length=40)
    detail = FroalaField()

    def __str__(self) -> str:
        return self.project_type

class Skill(models.Model):
    title = models.CharField(unique=True, max_length=30)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)
    validable = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['title']
   
    def __str__(self) -> str:
        return self.title
    

language_proficient = [
    ('basic', 'Basic'),
    ('limited_working_proficiency', 'Limited Working Proficiency'),
    ('professional_working_proficiency', 'Professional Working Proficiency'),
    ('native_proficiency', "Native Proficiency"),
]

class Language(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    language = models.CharField(max_length=30)
    proficient = models.CharField(max_length=40, choices=language_proficient)

    class Meta:
        ordering = ['language']
   
    def __str__(self) -> str:
        return self.language
    
class Bookmarks(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job = models.ForeignKey('Job_Posting', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True,blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.user.username)) + "-" + slugify(unidecode(self.job.title))+ '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.job.title


class Sector(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)

    def count_job_post(self) -> int:
        count = Job_Posting.objects.filter(sector_id = self.id).count()
        return count
    
    def count_interview_completed(self) -> int:
        applicant = Interviews.objects.filter(status='completed', application__job__sector_id = self.id).count()
        return applicant


    def __str__(self) -> str:
        return self.name
        


job_type = [
    ('full_time', 'Full Time'),
    ('part_time', 'Part Time'),
    ('freelance', 'Freelance'),
    ('internship', 'Internship'),
    ('seasonal ','seasonal'),
    ('contract', 'Contract'),
    ('remote', 'Remote'),
]

compensation_types = [
    ('monthly','Monthly'),
    ('yearly','Yearly'),
    ('hourly','Hourly'),
    ('commission','Commission'),
    ('bonus','Bonus'),
    ('benefits','Benefits')
]




CITY_CHOICES = (
        ('Addis Ababa', 'Addis Ababa'),
        ('Ērer Sātā', 'Ērer Sātā'),
        ('Shashemenē', 'Shashemenē'),
        ('K’ebrī Dehar', 'K’ebrī Dehar'),
        ('Nazrēt', 'Nazrēt'),
        ('Mekele', 'Mekele'),
        ('Godē', 'Godē'),
        ('Āwasa', 'Āwasa'),
        ('Dire Dawa', 'Dire Dawa'),
        ('Bahir Dar', 'Bahir Dar'),
        ('Sodo', 'Sodo'),
        ('Ārba Minch’', 'Ārba Minch’'),
        ('Desē', 'Desē'),
        ('Hosa’ina', 'Hosa’ina'),
        ('K’ebrī Beyah', 'K’ebrī Beyah'),
        ('Jijiga', 'Jijiga'),
        ('Dīla', 'Dīla'),
        ('Nek’emtē', 'Nek’emtē'),
        ('Debre Birhan', 'Debre Birhan'),
        ('Debre Mark’os', 'Debre Mark’os'),
        ('Ferfer', 'Ferfer'),
        ('Āwarē', 'Āwarē'),
        ('Harar', 'Harar'),
        ('Kombolcha', 'Kombolcha'),
        ('Jīma', 'Jīma'),
        ('Debre Tabor', 'Debre Tabor'),
        ('Harshin', 'Harshin'),
        ('Ādīgrat', 'Ādīgrat'),
        ('Debre Zeyit', 'Debre Zeyit'),
        ('Gambēla', 'Gambēla'),
        ('Mīzan Teferī', 'Mīzan Teferī'),
        ('Ādwa', 'Ādwa'),
        ('Gonder', 'Gonder'),
        ('Bodītī', 'Bodītī'),
        ('Āsela', 'Āsela'),
        ('Āksum', 'Āksum'),
        ('Bonga', 'Bonga'),
        ('Finote Selam', 'Finote Selam'),
        ('Semera', 'Semera'),
        ('Goba', 'Goba'),
        ('Hāgere Hiywet', 'Hāgere Hiywet'),
        ('Robē', 'Robē'),
        ('Yirga ‘Alem', 'Yirga ‘Alem'),
        ('Giyon', 'Giyon'),
        ('Bedēsa', 'Bedēsa'),
        ('Āzezo', 'Āzezo'),
        ('Butajīra', 'Butajīra'),
        ('Ālamat’ā', 'Ālamat’ā'),
        ('Āreka', 'Āreka'),
        ('Gīmbī', 'Gīmbī'),
        ('Wik’ro', 'Wik’ro'),
        ('Welk’īt’ē', 'Welk’īt’ē'),
        ('Metu', 'Metu'),
        ('Fichē', 'Fichē'),
        ('K’olīto', 'K’olīto'),
        ('Genet', 'Genet'),
        ('Āgaro', 'Āgaro'),
        ('Gelemso', 'Gelemso'),
        ('Āsosa', 'Āsosa'),
    )

    
class Job_Posting(models.Model):

JobPortal/templates/RMS/Interviewer/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="author" content="Themezhub" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Seraye Job Portal</title>
	<link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
	{% include 'include/head.html' %}
</head>

<body>
	
	
	<div id="main-wrapper">
		<div class="dashboard-wrap bg-light">
					 <!--Left Navbar-->
		  {% include 'RMS/interviewer/include/navbar.html'%}
		  {% include 'RMS/interviewer/include/topNavbar.html'%}
			<div class="dashboard-content">
				<div class="dashboard-tlbar d-block mb-5">
					<div class="row">
						<div class="colxl-12 col-lg-12 col-md-12">
							<h1 class="ft-medium">Hello, {{user.first_name|capfirst}} {{user.last_name|capfirst}}</h1>
							<img src="/media/{{user.image}}" alt="">
						</div>
					</div>
				</div>

			
				<div class="row justify-content-center">
					<div class="col-lg-6 card p-3">
						{% include 'CompanyAdmin/include/messages.html' %}
						<form method="post">
						  <div class="h3 text-center">Change Password</div>
						  <hr>
						  {% csrf_token %}
						  {{form.as_p}}
						<button class="btn btn-primary" type="submit">Save</button>
						</form>
					</div>
				  </div>

				
					
	<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
		<div class="col-md-4 d-flex align-items-center" bis_skin_checked="1">
		  <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
			<svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
		  </a>
		  <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Seraye, Inc</span>
		</div>
	
	  </footer>


			</div>

			

		</div>
		<!-- ======================= dashboard Detail End ======================== -->

		<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>


	</div>

	
	<!-- ============================================================== -->
	<!-- End Wrapper -->
	<!-- ============================================================== -->

	<!-- ============================================================== -->
	<!-- All Jquery -->
	<!-- ============================================================== -->
	<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/popper.min.js"></script>
	<script src="assets/js/bootstrap.min.js"></script>
	<script src="assets/js/slick.js"></script>
	<script src="assets/js/slider-bg.js"></script>
	<script src="assets/js/smoothproducts.js"></script>
	<script src="assets/js/snackbar.min.js"></script>
	<script src="assets/js/jQuery.style.switcher.js"></script>
	<script src="assets/js/custom.js"></script>
	<!-- ============================================================== -->
	<!-- This page plugins -->
	<!-- ============================================================== -->

</body>

<!-- Mirrored from themezhub.net/workplex-demo/workplex/employer-dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 08 Jul 2023 02:13:52 GMT -->

</html>

JobPortal/templates/RMS/Interviewer/personal-info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Themezhub" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>User Resume | Seraye Job Portal</title>
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
    {% include 'include/head.html' %}
  </head>

  <body>
    <div class="dashboard-wrap bg-light">
      <!--Left Navbar-->
      {% include 'RMS/Interviewer/include/navbar.html'%}

      <div class="dashboard-content">
        <div class="dashboard-tlbar d-block mb-5">
          <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
              <!-- Start home -->
              <section class="page-title-box" style="height: 0px">
                <div class="container">
                  <div class="row justify-content-center">
                    <div class="col-md-6">
                      <div class="text-center text-white">
                        <h3 class="mb-4">Resume</h3>
                        <div class="page-next">
                          <nav
                            class="d-inline-block"
                            aria-label="breadcrumb text-center"
                          >
                            <ol class="breadcrumb justify-content-center">
                              <li class="breadcrumb-item">
                                <a href="{% url 'index' %}">Home</a>
                              </li>
                              <li class="breadcrumb-item">
                                <a href="javascript:void(0)">Dashboard</a>
                              </li>
                              <li
                                class="breadcrumb-item active"
                                aria-current="page"
                              >
                                Edit Resume
                              </li>
                            </ol>
                          </nav>
                        </div>
                      </div>
                    </div>
                    <!--end col-->
                  </div>
                  <!--end row-->
                </div>
                <!--end container-->
              </section>
              <!-- end home -->
            </div>
          </div>
        </div>

        <div class="dashboard-widg-bar d-block">
          <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12">
              <div class="_dashboard_content bg-white rounded mb-4">
                <div class="_dashboard_content_header br-bottom py-3 px-3">
                  <div class="_dashboard__header_flex">
                    <h4 class="mb-0 ft-medium fs-md">
                      <i class="fa fa-file me-1 theme-cl fs-sm"></i>Create
                      Resume
                    </h4>
                  </div>
                </div>

                <div class="_dashboard_content_body py-3 px-3">
                  {% include 'RMS/messages.html' %}
                  <form class="row d-flex justify-content-center " method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-xl-10 col-lg-10col-md-12 col-sm-12 ">
                     <div class="row ">
                      <div class="col-xl-12 col-lg-12 mb-2">
                        <label for="id_photo">Upload Profile Picture less than 1 MB {% for err in form.photo.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label>
                        
                      {% if user.photo%}
                        <br>
                        <img src="/media/{{user.photo}}" class="img-fluid mx-auto d-block avatar-lg img-thumbnail rounded-circle mb-4" style="width: 200px; height: 200px;" alt="">
                        <br>
                       {% endif %}
                        {{form.photo}}
                      </div>
                     </div>
                      <div class="row mt-2 ">
                        <!--First Name-->
                        <div class="col-xl-6 col-lg-6">
                          <div class="form-group">
                            <label
                              class="text-dark ft-medium"
                              for="id_first_name"
                              >*First Name {% for err in form.first_name.errors %} <small class="text-danger"> {{err}} </small> {% endfor %} </label
                            >
                            {{form.first_name}}
                          </div>
                        </div>

                        <!--Last Name-->
                        <div class="col-xl-6 col-lg-6">
                          <div class="form-group">
                            <label
                              class="text-dark ft-medium"
                              for="id_last_name"
                              >*Last Name {% for err in form.last_name.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label
                            >
                            {{form.last_name}}
                          </div>
                        </div>

                        <!--Email-->
                        <div class="col-xl-12 col-lg-12">
                          <div class="form-group">
                            <label class="text-dark ft-medium" for="id_email"
                              >*Email {% for err in form.email.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label
                            >
                            {{form.email}}
                          </div>
                        </div>

                                      <!-- Save -->
                  <div class="row mb-5">
                    <div class="col-lg-12 col-md-12">
                      <button
                        type="submit"
                        class="btn btn-md ft-medium text-light rounded theme-bg"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>