CompanyAdmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='company-admin-dashboard'),

    path('job-posting/', views.job_posting, name='company-admin-job-posting'),
    path('company_interviewer/', views.company_interviewer, name='company_interviewer'),
    path('company_admins/', views.company_admins, name='company_admins'),
    path('company_user_detail/<str:id>/', views.company_user_detail, name='company_user_detail'),
    path('company_user_delete/<str:id>/', views.company_user_delete, name='company_user_delete'),
    path('change_status_user/<str:id>/', views.change_status_user, name='change_status_user'),

    path('company_admin_profile/', views.company_admin_profile, name='company_admin_profile'),
    path('company_admin_change_password/', views.company_admin_change_password, name='company_admin_change_password'),

    path('job-posting/<str:id>', views.job_detail, name='company-admin-job-posting-detail'),
    path('job-posting-delete/<str:id>', views.job_delete, name='company-admin-job-posting-delete'),

    #Applicant
    path('applicant/', views.applicant, name='company-admin-applicant'),
    path('applicant/<str:app_id>/', views.applicant_detail, name='company-admin-applicant-detail'),

    #Interview Status
    path('interview-status/', views.interview_status, name='company-admin-interview-status'),
    path('interview-status/<str:id>/', views.interview_status_detail, name='company-admin-interview-detail'),

    path('company_info/', views.company_info, name='company_info'),
    path('edit_company_info/<str:id>', views.edit_company_info, name='edit_company_info'),


    #Export Excel
    path('job-download/', views.export_job, name='company-export-job'),
    path('application-download/', views.export_application, name='company-export-application'),
    path('admin-download/', views.export_admins, name='company-export-admin'),
    path('interviewer-download/', views.export_interviewers, name='company-export-interviewers'),


    #Filter Candidates
     path('filter_candidates/<int:id>', views.filter_candidates, name='filter_candidates'), 
     path('find_candidate_detail/<int:id>', views.find_candidate_detail, name='find_candidate_detail'), 
       
]

Seraye/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobPortal.urls')),
    path('company/', include('Company.urls')),
     path('interview/', include('Interview.urls')),
    path('user-management/', include('UserManagement.urls')),
    path('user-admin/', include('UserAdmin.urls')),
    path('company-admin/', include('CompanyAdmin.urls')),
    path('froala_editor/', include('froala_editor.urls')),
]
urlpatterns += debug_toolbar_urls()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Company/models.py
from django.db import models
from django.utils.text import slugify
from froala_editor.fields import FroalaField
from unidecode import unidecode
import datetime
from phonenumber_field.modelfields import PhoneNumberField
from auditlog.registry import auditlog

# Create your models here.


# Create your models here.
class CompanyCatagory(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to="company/logo", null=True, blank=True)
    slogan = models.CharField(max_length=50, null=True, blank=True)
    active = models.BooleanField(default=False)
    about = FroalaField()
    email = models.EmailField( max_length=254)
    address = models.CharField(max_length=100)
    phone = PhoneNumberField()
    since = models.DateField(auto_now=False, auto_now_add=False , null=True , blank=True)
    views = models.IntegerField(default=0)
    total_jobs = models.IntegerField(default=0)
    website = models.URLField(max_length=200,null=True , blank=True)
    date_created = models.DateField(auto_now_add=True, null=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-date_created']

    
    

#Blog 
class Blog_Categories(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True,blank=True, editable=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.name)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
    
    def count_categories(self):
        return Blog.objects.filter(__type = self.name).count()
    
    def __str__(self) -> str:
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=200, blank=True)
    image = models.ImageField(upload_to='blog/')
    description = models.CharField(max_length=400)
    content = FroalaField()
    type = models.ManyToManyField(Blog_Categories)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at', '-updated_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
    
    def count_comment(self):
        return Comment.objects.filter(blog = self.id).count()
    
    def __str__(self) -> str:
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    comment = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self) -> str:
        return self.name

#Contact 
class Contact(models.Model):
    phone = PhoneNumberField()
    email = models.EmailField()
    location = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.email

class Social_Media(models.Model):
    name = models.CharField(max_length=30)
    link = models.URLField()

    def __str__(self) -> str:
        return self.name


class Contact_Message(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        ordering = ['-created_at'] #New's First



class FAQ(models.Model):
    question = models.CharField(max_length=70)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self) -> str:
        return self.question
    
    class Meta:
        ordering = ['-created_at'] #New's First



auditlog.register(CompanyCatagory)
auditlog.register(Blog_Categories)
auditlog.register(Blog)
auditlog.register(Social_Media)

CompanyAdmin/views.py
from django.shortcuts import render, redirect, HttpResponse ,  get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from JobPortal.forms import (JobPostingCompanyAdminForm, ApplicationForm, AdminInterviewForm,InterviewerForm)
from JobPortal.models import ( Job_Posting, Application, Candidate, Education, Experience, Sector, Interviews ,Project, Language , Certification)
from UserManagement.models import (CustomUser)
from django.db.models import Q
from django.contrib import messages 
from Company.models import Contact_Message , Company
from Company.forms import CompanyForm
from UserManagement.models import CustomUser 
from django.db.models import Count, Subquery
from UserManagement.forms import CustomUserCreationForm , CustomUserEditFormCompanyAdmin , CompanyAdmin , CustomUserEditFormAdmin , ChangePasswordForm
from UserManagement.decorators import (admin_user_required)
from django.contrib.auth import logout
import threading
from bs4 import BeautifulSoup
from JobPortal.resource import handle_telegram_post, handle_rejected_send_email, handle_hired_send_email
from JobPortal.resource import ( JobResource, ApplicationResource, UserResource)
# Create your views here.



@admin_user_required
def index(request):
    notification_application = Application.objects.filter(read = False).select_related()

    total_users = CustomUser.objects.filter(company = request.user.company).count()
    total_views = request.user.company.views
    total_jobs = Job_Posting.objects.filter(company = request.user.company).count()
    total_applicant = Application.objects.filter(job__company = request.user.company).count()
    sectors_with_job_counts = Sector.objects.annotate(job_posting_count=Count('job_posting', filter=Q(job_posting__company=request.user.company))).order_by('-job_posting_count').values_list('name', 'job_posting_count')[:15]
    sectors_with_job_counts_lists = [list(ele) for ele in sectors_with_job_counts]

    application_status_pending = Application.objects.filter(job__company = request.user.company, status = 'pending').count()
    application_status_in_review = Application.objects.filter(job__company = request.user.company, status = 'in_review').count()
    application_status_hired = Application.objects.filter(job__company = request.user.company, status = 'hired').count()
    application_status_rejected = Application.objects.filter(job__company = request.user.company, status = 'rejected').count()

    company_admins = CustomUser.objects.filter(company = request.user.company, is_admin = True).count()
    company_interviewers = CustomUser.objects.filter(company = request.user.company, is_interviewer = True).count()

    recent_jobs = Job_Posting.objects.filter(company = request.user.company)[:6]


    count_interview_status = Interviews.objects.filter( interviewer__company = request.user.company, status = 'completed', read = False).select_related().count()



    context = {
        'notification_application' : notification_application,
        'total_users' : total_users,
        'total_views' : total_views,
        'total_jobs' : total_jobs,
        'total_applicant' : total_applicant,
        'sectors_with_job_counts_lists' : sectors_with_job_counts_lists,
        'application_status_pending' : application_status_pending,
        'application_status_in_review' : application_status_in_review,
        'application_status_hired' : application_status_hired,
        'application_status_rejected' : application_status_rejected,
        'company_admins' : company_admins,
        'company_interviewers' : company_interviewers,
        'recent_jobs' : recent_jobs,
        'count_interview_status' : count_interview_status
    }
    return render(request, 'CompanyAdmin/index.html', context=context)


@admin_user_required
def job_posting(request):
    notification_application = Application.objects.filter(read = False).select_related()
    count_interview_status = Interviews.objects.filter( interviewer__company = request.user.company, status = 'completed', read = False).select_related().count()
    form = JobPostingCompanyAdminForm(request.POST or None, request.FILES or None)
    jobs = Job_Posting.objects.filter(company = request.user.company)
    count = 30
   
    if 'q' in request.GET:
        q = request.GET['q']
        jobs = Job_Posting.objects.filter( company = request.user.company).filter(Q(title__contains=q) | Q(sector__name__contains=q) | Q(salary_range_start__contains=q) | Q(salary_range_final__contains=q) | Q(type__contains=q))
    
    paginator = Paginator(jobs, 30) 
    page_number = request.GET.get('page')

    try:
        page = paginator.get_page(page_number)
        try: count = (30 * (int(page_number) if page_number  else 1) ) - 30
        except: count = (30 * (int(1) if page_number  else 1) ) - 30
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page = paginator.page(1)
        count = (30 * (int(1) if page_number  else 1) ) - 30
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page = paginator.page(paginator.num_pages)
        count = (30 * (int(paginator.num_pages) if page_number  else 1) ) - 30

    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            obj.company = request.user.company
            obj.save()
            form.save_m2m()

            slug = obj.slug
            title = obj.title
            sector = obj.sector
            description = BeautifulSoup(obj.description, 'html.parser').text
            experience = obj.experience
            vacancies = obj.vacancies
            location = obj.location 
            salary_range_start = obj.salary_range_start
            salary_range_final  = obj.salary_range_final
            type = obj.type
            date_closed = obj.date_closed
            skills = obj.skills.all()
            skill_names = [str(skill) for skill in skills]
            skills = ', '.join(skill_names)

            if obj.job_status:
                stop_event = threading.Event()
                background_thread = threading.Thread(target=handle_telegram_post, args=(request,slug,request.user.company, title, sector, vacancies, type, experience, description, skills, location, date_closed, salary_range_start, salary_range_final, stop_event), daemon=True)
                background_thread.start()
                stop_event.set()

            messages.success(request, '&#128515 Hello User, Successfully Updated')
            return redirect('company-admin-job-posting')
        else:
            messages.error(request, '&#128532 Hello User , An error occurred while updating Company')
            return redirect('company-admin-job-posting')
    
    
    context = {
        'notification_application' : notification_application,
        'jobs' : page,
        'count' : count,
        'form' : form,
        'count_interview_status' : count_interview_status
        
    }
    return render(request, 'CompanyAdmin/job_posting.html', context=context)



@admin_user_required
def company_interviewer(request):
    notification_application = Application.objects.filter(read = False).select_related()
    user = request.user
    company = user.company
    form = CompanyAdmin(request.POST or None, request.FILES or None)
    company_interviewer = CustomUser.objects.filter(is_interviewer=True , company=company)
    count = 30
    count_interview_status = Interviews.objects.filter( interviewer__company = request.user.company, status = 'completed', read = False).select_related().count()
   
    if 'q' in request.GET:
        q = request.GET['q']
        company_interviewer = CustomUser.objects.filter( Q(first_name__contains=q) |Q(last_name__contains=q) | Q(phone__icontains=q) | Q(email__icontains=q) , is_admin=True , company=company )
    
    paginator = Paginator(company_interviewer, 30) 
    page_number = request.GET.get('page')

    try:
        page = paginator.get_page(page_number)
        try: count = (30 * (int(page_number) if page_number  else 1) ) - 30
        except: count = (30 * (int(1) if page_number  else 1) ) - 30
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page = paginator.page(1)
        count = (30 * (int(1) if page_number  else 1) ) - 30
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page = paginator.page(paginator.num_pages)
        count = (30 * (int(paginator.num_pages) if page_number  else 1) ) - 30

    if request.method == 'POST':
        if form.is_valid():
            x = form.save(commit=False)
            x.is_interviewer =True
            x.company = company
            form.save()
            messages.success(request, '&#128515 Hello User, Successfully Added')
            return redirect('company_interviewer')
        else:
            messages.error(request, '&#128532 Hello User , An error occurred while Adding Company')
    

    
    context = {
        'notification_application' : notification_application,
        'company_interviewer' : page,
        'count' : count,
        'form' : form,
        'count_messages' : Contact_Message.objects.filter(is_read = False).count(),
        'count_interview_status' : count_interview_status
    }
    return render(request, 'CompanyAdmin/company_interviewer.html', context=context)
    

@admin_user_required
def company_admins(request):
    notification_application = Application.objects.filter(read = False).select_related()
    count_interview_status = Interviews.objects.filter( interviewer__company = request.user.company, status = 'completed', read = False).select_related().count()
    user = request.user
    company = user.company
    form = CompanyAdmin(request.POST or None, request.FILES or None)
    company_admins = CustomUser.objects.filter(is_admin=True , company=company)
    count = 30
   
    if 'q' in request.GET:
        q = request.GET['q']

templates/CompanyAdmin/company_admin_user_detail.html
{% load static %}
<!doctype html>
<html lang="en">

<!-- head-->
{% include 'CompanyAdmin/include/head.html' %}
{{ form.media }}
<!--/ head-->

<body data-sidebar="dark">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- Begin page -->
<div id="layout-wrapper">

    
    <!-- header-->
    {% include 'CompanyAdmin/include/sidebar.html' %}
    <!--/ header-->

   
    {% include 'CompanyAdmin/include/verticalBar.html' %}

    

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row justify-content-center">
                    <div class="col-8 card p-3">
                        {% include 'CompanyAdmin/include/messages.html' %}
                       <h2> Edit User</h2>
                       <hr>
                        {{ form.as_p }}
                       <div class="btn-group gap-2">
                        <a href="{% url 'company_admins' %}" class="btn btn-secondary"  type="submit">Cancel</a>
                        <button class="btn btn-primary" type="submit">Save</button>
                       </div>
                    </div>
                  </div>
                </form>
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
        {% include 'CompanyAdmin/include/footer.html' %}
    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->

</body>
</html>

templates/CompanyAdmin/edit_company_info.html
{% load static %}
<!doctype html>
<html lang="en">

<!-- head-->
{% include 'CompanyAdmin/include/head.html' %}
{{ form.media }}
<!--/ head-->

<body data-sidebar="dark">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- Begin page -->
<div id="layout-wrapper">

    
    <!-- header-->
    {% include 'CompanyAdmin/include/sidebar.html' %}
    <!--/ header-->

   
    {% include 'CompanyAdmin/include/verticalBar.html' %}

    

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        
        <div class="page-content">
            <div class="container-fluid">
              <div class="row justify-content-center">
                <div class="col-11">
                  <div class="card p-4">
                    <div class="card-body text-center">
                      <h3 class="text-info">Edit Company Information</h3>
                      <h4 class="text-info">{{company.name | capfirst}}  </h4>

                    </div>
                  </div>
                </div>

               

               <div class="col-lg-8 card shadow p-5s">
                
                      <form  method="post" enctype="multipart/form-data">
                        <div >
                          {% csrf_token %}
                          {{form.as_p}}
                        </div>
                        <div >
                        
                           <button type="submit" class="btn btn-primary mb-5">Save</button>
                          
                        </div>
              
                      </form>
               </div>

              </div>
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
        {% include 'CompanyAdmin/include/footer.html' %}
    </div>
    <!-- end main content-->



</body>
</html>

templates/CompanyAdmin/interview_status_detail.html
{% load static %}
<!doctype html>
<html lang="en">

<!-- head-->
{% include 'CompanyAdmin/include/head.html' %}
{{ form.media }}
<!--/ head-->

<body data-sidebar="dark">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- Begin page -->
<div id="layout-wrapper">

    
    <!-- header-->
    {% include 'CompanyAdmin/include/sidebar.html' %}
    <!--/ header-->

   
    {% include 'CompanyAdmin/include/verticalBar.html' %}

    

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">
              <div class="row justify-content-center">
                <div class="col-12">
                  {% include 'CompanyAdmin/include/messages.html' %}        
                  <div class="card">
                    <div class="card-body text-center">
                      <h4 class="p-3">{{interview.application.job.title}}</h4>
                      <hr>
                    </div>
                  </div>
                </div>

               

                <div class="col-xl-4">
                  <div class="card p-4">
                    <div class="card-body text-center">
                      <div class="text-center pb-4 border-bottom">
                        <img src="/media/{{interview.application.user.candidate.photo}}" alt=""
                          class="avatar-lg img-thumbnail rounded-circle mb-4" />
                        <h5 class="mb-0">{{interview.application.user.first_name}} {{interview.application.user.last_name}}</h5>
                        <!--<p class="text-muted">Developer</p>-->
                        <ul class="candidate-detail-social-menu mt-3 list-inline mb-0">
                          {% if interview.application.user.candidate.linked_in%}
                          
                          <li class="list-inline-item">
                            <a href="{{interview.application.user.candidate.linked_in}}" class=" social-link rounded-3 btn-soft-info">
                              <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                              </svg>
                            </a>
                          </li>
                          {% endif %}
                        </ul>

                        <hr>

                        <div class="mt-4 text-start">
                          <h5 class="fs-17 fw-bold mb-3">Contacts</h5>


                          <div class="d-flex  p-2 justify-content-between">
                            <label class=" text-muted " for="">Email: </label>
                          <div>
                            <p class="text-muted text-break mb-0 text-sm">
                              {{interview.application.user.candidate.email}}
                            </p>
                          </div>
                          </div>


                          <div class="d-flex  p-2 justify-content-between">
                            <label class=" text-muted  " for="">Phone</label>
                          <div>
                            <p class="text-muted text-break mb-0">
                              {{interview.application.user.candidate.phone1}}
                            </p>
                          </div>
                          </div>


                          <div class="d-flex  p-2 justify-content-between">
                            <label class=" text-muted " for="">Address</label>
                          <div>
                            <p class="text-muted text-break mb-0">
                              {{interview.application.user.candidate.address}}
                            </p>
                          </div>
                          </div>

                          <div class="text-start boarder mt-3">
                            <h4>Job Status</h4>
                            <form method="post">
                              {% csrf_token %}
                              {{interview_form}}
                              <div class="text-end mt-3">
                                <button type="submit" class="btn btn-primary">Submit</button>
                              </div>
                            </form>
                          </div>


                        </div>
                        
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-xl-8">
                  <div class="card p-4">
                    <div class="card-body  text-center">

                      <ul class="profile-content-nav nav nav-pills border-bottom mb-4" id="pills-tab" role="tablist">
                        <li class="nav-item" role="presentation">

                          <button class="nav-link fs-3">
                            Job Status
                          </button>
                        </li>
                      </ul>

                      <div class="text-start boarder">
                        <h4>Interview Status</h4>
                        <p class="p-1 text-muted">Date Scheduled: {{interview.date_schedule}}</p>
                        <p class="p-1 text-muted">Time Scheduled: {{interview.time_schedule}}</p>
                        <p class="p-1 text-muted">Interview Type: {{interview.get_type_display}}</p>
                        <p class="p-1 text-muted">Interview Status: <span class="fw-bold">{{interview.get_status_display}}</span></p>
                        <div class="p-1 text-muted border border-primary"><span class="h4 fw-bold">Interview Note:</span> <span>{{interview.note | safe }}</span></div>
                      </div>

                      <hr class="p-2"> 
                    
                      <hr>

                      

                    </div>
                  </div>
                </div>


              </div>
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
        {% include 'CompanyAdmin/include/footer.html' %}
    </div>
    <!-- end main content-->



<!--Detail Company Modal-->
  <!-- Modal -->
  <div class="modal fade" id="detailJobs" tabindex="-1" aria-labelledby="detailJobsLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="detailJobsLabel">Company Information</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div id="detailModalBody" class="modal-body">
        </div>
    </div>
  </div>
</div>
<!--End Modal -->

<!--Add Company Modal-->
  <!-- Modal -->
  <div class="modal fade" id="AddJob" tabindex="-1" aria-labelledby="AddJobLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="AddJobLabel">Company Information</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form  method="post" enctype="multipart/form-data">
          <div id="detailModalBody" class="modal-body">
            {% csrf_token %}
            {{form.as_p}}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
             <button type="submit" class="btn btn-primary">Save</button>
            
          </div>

        </form>
    </div>
  </div>
</div>
<!--End Modal -->

<!--Delete  Modal-->
  <!-- Modal -->
  <div class="modal fade" id="deleteJobModal" tabindex="-1" aria-labelledby="deleteJobModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteJobModalLabel">Delete Responsible Ministry</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="h4 fw-normal" id="deleteJob"></p>
        </div> 
          
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a href="#" id="deleteJobAnchor" type="submit" class="btn btn-danger">Delete</a>
        </div>
        
      </div>
    </div>
  </div>
  <!--End Modal -->



</div>
<!-- END layout-wrapper -->

</body>
</html>